version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - testnet

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Enable HTTPS
      KEYCLOAK_HTTPS_PORT: "8443"
      KEYCLOAK_HTTPS_PROXY_PORT: "443"
      KEYCLOAK_HTTP_PORT: "8080"
      # Example: Generate a self-signed certificate
      KEYCLOAK_HTTPS_CERTIFICATE: "/etc/x509/https/keycloak.crt"
      KEYCLOAK_HTTPS_CERTIFICATE_KEY: "/etc/x509/https/keycloak.key"
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - postgres
    networks:
      - testnet

networks:
  testnet:
    external: true
